/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp_JavaInterface */

#ifndef _Included_cpp_JavaInterface
#define _Included_cpp_JavaInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_JavaInterface
 * Method:    createNewDatabase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cpp_JavaInterface_createNewDatabase
  (JNIEnv *, jobject);

/*
 * Class:     cpp_JavaInterface
 * Method:    executeQuery
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cpp_JavaInterface_executeQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cpp_JavaInterface
 * Method:    importDatabase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cpp_JavaInterface_importDatabase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cpp_JavaInterface
 * Method:    exportDatabase
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cpp_JavaInterface_exportDatabase
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
